### ISSUE TITLE
[Feature Request] Creating lists by separating them into subdomains (ex: .co.uk, .com.tr)

### ISSUE THREAD

**Issue by ramazansancar** [dontcrash/NRD#1]
How does such a feature come about?

**Comment by dontcrash** [comment]
Check out https://github.com/dontcrash/NRD/blob/main/update.py
It pulls NRD lists and splits them into TLD.
If there is no .co.uk etc it means that the upstream NRD list is not providing them.
If I had access to a larger NRD list with more TLD's, it would be possible to have individual lists for say .com.tr etc
